---
- name: plan to restart openresty
  set_fact:
    __openresty_restart: true

- name: plan to reload openresty
  set_fact:
    __openresty_reload: true

- name: reload openresty
  shell: >
    docker exec {{openresty_docker_name}} nginx -s reload && echo 'yes'
  register: __reload_openresty
  changed_when: (__reload_openresty.stdout_lines | last) == 'yes'
